server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


#Sustituir lo de arriba por lo de abajo después de subir lo de arriba al repo publico y cambiar la url en el yml de config
#
#spring:
#  application:
#    name: catalog-service
#  config:
#    import: optional:configserver:http://localhost:8888

# al copiar lo de arriba al repo publico, renombrar el archivo para catalog-service.yml
